build:
    environment:
        php: '7.4.0'
    
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage.xml'
                coverage:
                    file: 'coverage.xml'
                    format: 'clover'

before_commands:
    - "composer install --prefer-source"

checks:
    php:
        code_rating: true
        duplication: true
        
tools:
    external_code_coverage: true